name: GitHub Actions Demo
on: [push]
jobs:
  my-first-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 # checks out the repository code so the workflow can access files in your GitHub repository
      - name: Say Hello
        run : |
          echo "Hello World"
      - name: run python script
        run: |
          pip install -r scripts/requirments
          python scripts/ci.py

