# This workflow is triggered on a push event to the repository
on : push

# 'jobs' defines the list of tasks (jobs) that the workflow will execute
jobs:
  # 'screts' is the unique identifier (ID) for this specific job
  screts:
    # 'runs-on' specifies the type of machine (runner) to execute the job on
    # In this case, it uses the latest available version of Ubuntu
    runs-on: ubuntu-latest  
    
    # 'steps' contains the sequence of tasks to be executed in this job. 
    # In YAML, a colon (:) denotes a key-value pair, while a hyphen (-) denotes an item in a list.
    steps:
      # The hyphen (-) here indicates that this is an item in the 'steps' list.
      # This specific step executes a shell command using 'run'.
      - run: |
          import os
          print(f'The length of the secret is {len(os.getenv("MY_SECRET"))}', while the length of the second variable is {len(os.getenv("MY_VAR2"))}')
        # 'env' sets environment variables that are available to this step
        shell: python
        env: 
          # 'MY_VAR' is the name of the environment variable being set
          # '${{ secrets.MY_SECRET}}' uses GitHub Actions expression syntax to access an encrypted secret named 'MY_SECRET' stored in the repository settings
          MY_VAR: ${{ secrets.MY_SECRET}}
          MY_VAR2: This_is_The_Second_Variable
