name: trigger-demo-workflow # Name of the workflow
on: 
    push:
        branches:
            - main # Trigger the workflow on push events only to the main branch
    pull_request: # Trigger the workflow on pull request events to any branch
    workflow_dispatch: # Manually trigger the workflow from the GitHub Actions tab
    
jobs:
  trigger-demo: # Name of the job
    runs-on: ubuntu-latest # Type of runner to use
    steps:
      - run: echo "Hello" # Run a shell command

